p7: p7.o readline.o
	gcc -o p7 p7.o readline.o
p7.o: p7.c readline.h
	gcc -c p7.c
p3: p3.o readline.o
	gcc -o p3 p3.o readline.o
p3.o: p3.c readline.h
	gcc -c p3.c
p1: p1.o readline.o
	gcc -o p1 p1.o readline.o
p1.o: p1.c readline.h
	gcc -c p1.c
readline.o: readline.c readline.h
	gcc -c readline.c
